/**
 * Grove Bluehawk Runner
 *
 * CLI wrapper for running bluehawk snip --dry-run to preview snippet output.
 */

import * as vscode from "vscode";
import { execFile } from "child_process";
import { promisify } from "util";
import * as path from "path";
import * as fs from "fs";
import * as os from "os";

const execFileAsync = promisify(execFile);

export interface BluehawkSnippet {
  /** Name of the snippet */
  name: string;
  /** The extracted content */
  content: string;
  /** Original file path */
  sourcePath: string;
  /** Language for syntax highlighting */
  language?: string;
  /** Line numbers in original file */
  sourceRange?: {
    start: number;
    end: number;
  };
}

export interface BluehawkResult {
  /** Whether the command succeeded */
  success: boolean;
  /** Extracted snippets */
  snippets: BluehawkSnippet[];
  /** Error message if failed */
  error?: string;
  /** Raw output from bluehawk */
  rawOutput?: string;
}

/**
 * Get the bluehawk CLI command as a binary + args tuple.
 * Uses the setting if provided, otherwise defaults to npx bluehawk.
 * Returns separate bin and args so callers can use execFile (no shell).
 */
function getBluehawkCommand(): { bin: string; baseArgs: string[] } {
  const config = vscode.workspace.getConfiguration("grove");
  const customPath = config.get<string>("bluehawkPath", "").trim();
  if (customPath.length > 0) {
    return { bin: customPath, baseArgs: [] };
  }
  // Default: invoke bluehawk via npx so it doesn't need a global install
  return { bin: "npx", baseArgs: ["bluehawk"] };
}

/**
 * Check if a file contains Bluehawk directives.
 */
export function containsBluehawkDirectives(content: string): boolean {
  // Check for common Bluehawk markers
  const markers = [
    ":snippet-start:",
    ":snippet-end:",
    ":remove-start:",
    ":remove-end:",
    ":replace-start:",
    ":replace-end:",
    ":uncomment-start:",
    ":uncomment-end:",
    ":emphasize-start:",
    ":emphasize-end:",
  ];

  return markers.some((marker) => content.includes(marker));
}

/**
 * Run bluehawk snip to extract snippets from a file.
 * Uses a temporary directory for output.
 */
export async function runBluehawkDryRun(
  filePath: string,
): Promise<BluehawkResult> {
  const workingDir = path.dirname(filePath);

  // Create a temporary directory for output
  const tempDir = await fs.promises.mkdtemp(
    path.join(os.tmpdir(), "grove-bluehawk-"),
  );

  try {
    // Run bluehawk snip with output to temp directory.
    // execFile avoids shell interpolation — args are passed directly to the process.
    const { bin, baseArgs } = getBluehawkCommand();
    await execFileAsync(bin, [...baseArgs, "snip", "-o", tempDir, filePath], {
      cwd: workingDir,
      timeout: 30000, // 30 second timeout
    });

    // Read the generated snippet files from temp directory
    const snippets = await readSnippetsFromDir(tempDir, filePath);

    return {
      success: true,
      snippets,
    };
  } catch (error) {
    // Handle execution errors
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Check if bluehawk is not installed
    if (errorMessage.includes("not found") || errorMessage.includes("ENOENT")) {
      return {
        success: false,
        snippets: [],
        error: "Bluehawk CLI not found. Install with: npm install -g bluehawk",
      };
    }

    // Check if no snippets were found (not an error, just empty)
    if (errorMessage.includes("No snippets found")) {
      return {
        success: true,
        snippets: [],
      };
    }

    return {
      success: false,
      snippets: [],
      error: `Bluehawk execution failed: ${errorMessage}`,
    };
  } finally {
    // Clean up temp directory
    try {
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
  }
}

/**
 * Read snippet files from a directory generated by bluehawk.
 */
async function readSnippetsFromDir(
  dir: string,
  sourcePath: string,
): Promise<BluehawkSnippet[]> {
  const snippets: BluehawkSnippet[] = [];

  try {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        // Recursively read subdirectories
        const subSnippets = await readSnippetsFromDir(fullPath, sourcePath);
        snippets.push(...subSnippets);
      } else if (entry.isFile()) {
        // Read the snippet file
        const content = await fs.promises.readFile(fullPath, "utf-8");
        const ext = path.extname(entry.name);
        const name = path.basename(entry.name, ext);

        snippets.push({
          name,
          content,
          sourcePath,
          language: detectLanguage(sourcePath),
        });
      }
    }
  } catch {
    // Ignore read errors
  }

  return snippets;
}

/**
 * Detect language from file extension for syntax highlighting.
 */
function detectLanguage(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  const languageMap: Record<string, string> = {
    ".js": "javascript",
    ".ts": "typescript",
    ".jsx": "javascriptreact",
    ".tsx": "typescriptreact",
    ".py": "python",
    ".java": "java",
    ".kt": "kotlin",
    ".cs": "csharp",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".swift": "swift",
    ".m": "objective-c",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".xml": "xml",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".sh": "shell",
    ".bash": "shell",
    ".md": "markdown",
    ".rst": "restructuredtext",
  };

  return languageMap[ext] || "plaintext";
}
